#!/usr/bin/env ruby

require 'date'
require 'fileutils'

DATE = ENV["DATE"] || DateTime.now
TITLE = ENV["TITLE"] || 'Henrique F. Teixeira'
EDITOR = ENV["EDITOR"] || 'vim'
REPORT_DIR = ENV["REPORT_DIR"] || File.dirname(__FILE__)

FileUtils.mkdir_p("#{REPORT_DIR}/#{DATE.strftime("%Y/%m")}")

unless File.exist?("#{REPORT_DIR}/#{DATE.strftime("%Y/%m/%d")}.md")
  File.open("#{REPORT_DIR}/#{DATE.strftime("%Y/%m/%d")}.md",'w+') do |f|
    f.puts("# #{DATE.strftime("%d/%m/%Y")} - #{TITLE}\n\n")
    f.puts("### Atividades:\n\n")
    f.puts("- [ ]\n\n")
    f.puts("---\n\n")
    f.puts("### Reuniões:\n\n")
    f.puts("---\n\n")
    f.puts("### Anotações:\n\n")
    f.puts("###### Anotações de Reunião:\n\n")
    f.puts("---\n\n")
    f.puts("### Interrupções:\n\n")
    f.puts("---\n\n")
    f.puts("### Dificuldades:\n\n")
    f.puts("---\n\n")
    f.puts("### Pomodoros:\n\n")
    f.puts("0\n\n")
    f.puts("---\n\n")
    f.puts("### Ponto:\n\n")
    f.puts("- \n\n")
  end
end

system("cd #{REPORT_DIR}/ && #{EDITOR} #{DATE.strftime("%Y/%m/%d")}.md")

exit
